<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 27,
                'name' => 'Ženska haljina Sloga MB',
                'slug' => 'zenska-haljina-sloga-mb',
                'details' => NULL,
                'price' => 1450,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 81,
                'manufacturer_id' => 6,
                'image' => 'products\\August2020\\7dxvV6LbV9rF13OMd6YL.jpg',
                'images' => '["products\\\\August2020\\\\VIi2utj4bVPCTgM35gYX.jpg","products\\\\August2020\\\\yXv3V0jYrttkLSwKWslv.jpg"]',
                'created_at' => '2020-08-20 11:34:58',
                'updated_at' => '2020-08-20 14:22:41',
            ),
            1 => 
            array (
                'id' => 28,
                'name' => 'Cool Boy duks',
                'slug' => 'cool-boy-duks',
                'details' => NULL,
                'price' => 750,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 15,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\vb3cJVoxzQstYSH0j02d.jpg',
                'images' => '["products\\\\August2020\\\\8zFLJ5rmamZzJLFuPzUl.jpg","products\\\\August2020\\\\JEJcQGfrA9c6MUguIdeR.jpg","products\\\\August2020\\\\AyLTS2eRyl1x75tzId5l.jpg"]',
                'created_at' => '2020-08-20 11:47:23',
                'updated_at' => '2020-08-20 14:23:27',
            ),
            2 => 
            array (
                'id' => 29,
                'name' => 'Duks za devojčice Kid Star',
                'slug' => 'duks-za-devojcice-kid-star',
                'details' => NULL,
                'price' => 890,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 53,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\BcqHY9wUCtnZLMxfXzPX.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 11:50:58',
                'updated_at' => '2020-08-20 14:23:01',
            ),
            3 => 
            array (
                'id' => 30,
                'name' => 'Duks Urban Style',
                'slug' => 'duks-urban-style',
                'details' => NULL,
                'price' => 1390,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 29,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\5B9WsQYj9L5IFhqg0JPz.jpg',
                'images' => '["products\\\\August2020\\\\ETBMIXWALoaT0HadriLU.jpg","products\\\\August2020\\\\kT6ZuFqfJrmlL7E24n2H.jpg"]',
                'created_at' => '2020-08-20 11:54:01',
                'updated_at' => '2020-08-20 14:21:17',
            ),
            4 => 
            array (
                'id' => 31,
                'name' => 'Majica "Made with love"',
                'slug' => 'majica-made-with-love',
                'details' => NULL,
                'price' => 1390,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 45,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\LxvzFxdiJc9iXbaX5Iy7.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 12:00:12',
                'updated_at' => '2020-08-20 14:22:11',
            ),
            5 => 
            array (
                'id' => 32,
                'name' => 'Duks "1976"',
                'slug' => 'duks-1976',
                'details' => NULL,
                'price' => 990,
                'description' => NULL,
                'quantity' => 4,
                'category_id' => 29,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\e5WHX4FaKq3bEkdtRm9p.jpg',
                'images' => '["products\\\\August2020\\\\LOs0CJq5t00hZ4ioSTkz.jpg","products\\\\August2020\\\\bp70VkmhHjNuhJe4C1wR.jpg"]',
                'created_at' => '2020-08-20 12:02:13',
                'updated_at' => '2020-08-20 14:20:48',
            ),
            6 => 
            array (
                'id' => 34,
                'name' => 'Duks za devojčice "Simplify"',
                'slug' => 'duks-za-devojcice-simplify',
                'details' => NULL,
                'price' => 1190,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 53,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\aAqKMQosVw5k8evypBJt.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 12:04:48',
                'updated_at' => '2020-08-20 14:20:26',
            ),
            7 => 
            array (
                'id' => 35,
                'name' => 'Haljinica za bebe "Love"',
                'slug' => 'haljinica-za-bebe-love',
                'details' => NULL,
                'price' => 1050,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 9,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\rQYPDsdkUvNPMtONsNiG.jpg',
                'images' => '["products\\\\August2020\\\\JQOSKuOwk4b9UGWMcHtp.jpg","products\\\\August2020\\\\XCehS96Ek8lIFDD46Lus.jpg"]',
                'created_at' => '2020-08-20 12:08:27',
                'updated_at' => '2020-08-20 12:12:03',
            ),
            8 => 
            array (
                'id' => 36,
                'name' => 'Zeka za devojčice "Jednorog"',
                'slug' => 'zeka-za-devojcice-jednorog',
                'details' => NULL,
                'price' => 570,
                'description' => NULL,
                'quantity' => 7,
                'category_id' => 4,
                'manufacturer_id' => 2,
                'image' => 'products\\August2020\\dVF0l1an2qsVm65nFpYz.jpg',
                'images' => '["products\\\\August2020\\\\5oZFLQYhOBO5OIfVkV3c.jpg","products\\\\August2020\\\\ZC3qW7hyYmGNIVL5ZF2p.jpg","products\\\\August2020\\\\KpwMxETM7Z8mWLeyGUOG.jpg","products\\\\August2020\\\\iw6Ji8hvKzdijDMT6MZF.jpg"]',
                'created_at' => '2020-08-20 12:17:40',
                'updated_at' => '2020-08-20 12:17:40',
            ),
            9 => 
            array (
                'id' => 37,
                'name' => 'Zeka za devojčice "Ooh Daris"',
                'slug' => 'zeka-za-devojcice-ooh-daris',
                'details' => NULL,
                'price' => 530,
                'description' => NULL,
                'quantity' => 7,
                'category_id' => 4,
                'manufacturer_id' => 2,
                'image' => 'products\\August2020\\XBm4aH0PIURu2dyCcygh.jpg',
                'images' => '["products\\\\August2020\\\\G7i80RuxesMgI9E2mreP.jpg","products\\\\August2020\\\\lj5Q1WBX9yatclhp8fKQ.jpg","products\\\\August2020\\\\bZsT365iZCTXPf8BYrxk.jpg"]',
                'created_at' => '2020-08-20 12:21:22',
                'updated_at' => '2020-08-20 12:21:22',
            ),
            10 => 
            array (
                'id' => 38,
                'name' => 'Džemper za dečake "Bambino"',
                'slug' => 'dzemper-za-decake-bambino',
                'details' => NULL,
                'price' => 1190,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 30,
                'manufacturer_id' => 1,
                'image' => 'products\\August2020\\UzBRtY9vAH9rT7wK0RXc.jpg',
                'images' => '["products\\\\August2020\\\\709bFpjxTVY9YLzcZJFM.jpg","products\\\\August2020\\\\p0T5Mq9KchJ2J4RIvjtA.jpg","products\\\\August2020\\\\7ab5YJrIZdJN3Ng81VqD.jpg"]',
                'created_at' => '2020-08-20 12:25:59',
                'updated_at' => '2020-08-20 14:19:48',
            ),
            11 => 
            array (
                'id' => 39,
                'name' => 'Trenerka za devojčice "Inpsiration"',
                'slug' => 'trenerka-za-devojcice-inpsiration',
                'details' => NULL,
                'price' => 2190,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 50,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\ZjeQwrgK4EoB0aOHOoLi.jpg',
                'images' => '["products\\\\August2020\\\\RP0G4OYUPjd4rIANGd2v.jpg","products\\\\August2020\\\\UrVT2E331IpUHUmkHZSD.jpg"]',
                'created_at' => '2020-08-20 13:29:24',
                'updated_at' => '2020-08-20 14:19:29',
            ),
            12 => 
            array (
                'id' => 40,
                'name' => 'Tregerice za bebe Bambino',
                'slug' => 'tregerice-za-bebe-bambino',
                'details' => NULL,
                'price' => 1700,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 16,
                'manufacturer_id' => 1,
                'image' => 'products\\August2020\\C0WFsmcxdwjCBHONlXVV.jpg',
                'images' => '["products\\\\August2020\\\\J15P8frKOYwfRAzSljVq.jpg","products\\\\August2020\\\\W8qy0Ugi3GDwZQlsGSz3.jpg"]',
                'created_at' => '2020-08-20 13:38:35',
                'updated_at' => '2020-08-20 13:39:12',
            ),
            13 => 
            array (
                'id' => 41,
                'name' => 'Posteljina za bebe Hajdi',
                'slug' => 'posteljina-za-bebe-hajdi',
                'details' => NULL,
                'price' => 4200,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 92,
                'manufacturer_id' => 7,
                'image' => 'products\\August2020\\sMLBfPwzQ5R8D0S4OApu.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 13:41:23',
                'updated_at' => '2020-08-20 14:19:10',
            ),
            14 => 
            array (
                'id' => 42,
                'name' => 'Farmerice za devojčice Bambino',
                'slug' => 'farmerice-za-devojcice-bambino',
                'details' => NULL,
                'price' => 1800,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 49,
                'manufacturer_id' => 1,
                'image' => 'products\\August2020\\QtYwCJ1BYMtZ2hen71Cj.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 13:44:47',
                'updated_at' => '2020-08-20 14:18:47',
            ),
            15 => 
            array (
                'id' => 43,
                'name' => 'Farmerke za dečake Bambino',
                'slug' => 'farmerke-za-decake-bambino',
                'details' => NULL,
                'price' => 1700,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 33,
                'manufacturer_id' => 1,
                'image' => 'products\\August2020\\i3k1daZ5axfmnSZK00V3.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 13:46:18',
                'updated_at' => '2020-08-20 13:46:18',
            ),
            16 => 
            array (
                'id' => 44,
                'name' => 'Ćebe za bebe "Meda" - Radović',
                'slug' => 'cebe-za-bebe-meda-radovic',
                'details' => NULL,
                'price' => 1200,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 92,
                'manufacturer_id' => 4,
                'image' => 'products\\August2020\\yWuqiHOgvkc9xNUkh2lk.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 13:48:11',
                'updated_at' => '2020-08-20 14:18:21',
            ),
            17 => 
            array (
                'id' => 45,
                'name' => 'Ćebe za bebe "Baby bunny" - Radović',
                'slug' => 'cebe-za-bebe-baby-bunny-radovic',
                'details' => NULL,
                'price' => 1300,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 92,
                'manufacturer_id' => 4,
                'image' => 'products\\August2020\\3BuSpfLG9JgKeR6vwiUy.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 13:50:07',
                'updated_at' => '2020-08-20 14:18:04',
            ),
            18 => 
            array (
                'id' => 46,
                'name' => 'Ćebe za bebe "Slonče" Hajdi',
                'slug' => 'cebe-za-bebe-slonce-hajdi',
                'details' => NULL,
                'price' => 1060,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 92,
                'manufacturer_id' => 7,
                'image' => 'products\\August2020\\3ZDk0JITJ76YRf9IOiRL.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 13:52:03',
                'updated_at' => '2020-08-20 14:17:49',
            ),
            19 => 
            array (
                'id' => 47,
                'name' => 'Bade mantil za devojčice Hajdi',
                'slug' => 'bade-mantil-za-devojcice-hajdi',
                'details' => NULL,
                'price' => 1550,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 61,
                'manufacturer_id' => 7,
                'image' => 'products\\August2020\\YDlQXX29lusSRieQCweF.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 13:55:07',
                'updated_at' => '2020-08-20 13:58:16',
            ),
            20 => 
            array (
                'id' => 48,
                'name' => 'Bade mantil za dečake Hajdi',
                'slug' => 'bade-mantil-za-decake-hajdi',
                'details' => NULL,
                'price' => 1550,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 42,
                'manufacturer_id' => 7,
                'image' => 'products\\August2020\\jVHaBUmVOiNa3TQ0LBhQ.jpg',
                'images' => '["products\\\\August2020\\\\CjC8XpC7vSWC0amcE4bl.jpg","products\\\\August2020\\\\RxwppNAmsprYPrBlcW0w.jpg"]',
                'created_at' => '2020-08-20 13:59:56',
                'updated_at' => '2020-08-20 13:59:56',
            ),
            21 => 
            array (
                'id' => 49,
                'name' => 'Haljina "Just Love Sun"',
                'slug' => 'haljina-just-love-sun',
                'details' => NULL,
                'price' => 780,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 46,
                'manufacturer_id' => 2,
                'image' => 'products\\August2020\\WQO9StlO6Hjo5XIXli3B.jpg',
                'images' => '["products\\\\August2020\\\\OQiwVbXanzatCTc2MqlF.jpg","products\\\\August2020\\\\tOnAKIy5fkj3tkR10KCE.jpg"]',
                'created_at' => '2020-08-25 13:57:22',
                'updated_at' => '2020-08-25 13:57:22',
            ),
            22 => 
            array (
                'id' => 50,
                'name' => 'Haljina "I woke up like this"',
                'slug' => 'haljina-i-woke-up-like-this',
                'details' => NULL,
                'price' => 1050,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 46,
                'manufacturer_id' => 1,
                'image' => 'products\\August2020\\KnZWvuvfethV2BNZFagk.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 14:01:38',
                'updated_at' => '2020-08-25 14:01:38',
            ),
            23 => 
            array (
                'id' => 51,
                'name' => 'Cvetna haljina za devojčice Model kids',
                'slug' => 'cvetna-haljina-za-devojcice-model-kids',
                'details' => NULL,
                'price' => 550,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 46,
                'manufacturer_id' => 2,
                'image' => 'products\\August2020\\YW0ZbxjBBXCA6dBhUCTX.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 14:04:32',
                'updated_at' => '2020-08-25 14:04:32',
            ),
            24 => 
            array (
                'id' => 52,
                'name' => 'Haljina za devojčice "Be Lovely" Model Kids',
                'slug' => 'haljina-za-devojcice-be-lovely-model-kids',
                'details' => NULL,
                'price' => 780,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 46,
                'manufacturer_id' => 2,
                'image' => 'products\\August2020\\Jnebu0lLgAeTDznKiF9b.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 14:07:00',
                'updated_at' => '2020-08-25 14:07:00',
            ),
            25 => 
            array (
                'id' => 53,
                'name' => 'Haljina za devojčice "Sailing Blue" Bambino',
                'slug' => 'haljina-za-devojcice-sailing-blue-bambino',
                'details' => NULL,
                'price' => 950,
                'description' => NULL,
                'quantity' => 4,
                'category_id' => 46,
                'manufacturer_id' => 1,
                'image' => 'products\\August2020\\fjBB3Q3VHkfnrE0yqqg2.jpg',
                'images' => '["products\\\\August2020\\\\Wjaxs1SCAFRNpUZ3c3E7.jpg","products\\\\August2020\\\\yCgQXngpEG2iSHj7NkfP.jpg"]',
                'created_at' => '2020-08-25 14:10:03',
                'updated_at' => '2020-08-25 14:10:03',
            ),
            26 => 
            array (
                'id' => 54,
                'name' => 'Haljina za devojčice "Višnje" Panter',
                'slug' => 'haljina-za-devojcice-visnje-panter',
                'details' => NULL,
                'price' => 1200,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 46,
                'manufacturer_id' => 3,
                'image' => 'products\\August2020\\DMt6JXtHJG9E1eR7KLhM.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 14:13:22',
                'updated_at' => '2020-08-25 14:13:22',
            ),
            27 => 
            array (
                'id' => 55,
                'name' => 'Haljina za devočice "Srca" Panter',
                'slug' => 'haljina-za-devocice-srca-panter',
                'details' => NULL,
                'price' => 1200,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 46,
                'manufacturer_id' => 3,
                'image' => 'products\\August2020\\SBnptiLsKFT9402SWvUy.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 14:14:13',
                'updated_at' => '2020-08-25 14:14:13',
            ),
            28 => 
            array (
                'id' => 56,
                'name' => 'Haljina za devojčice "MDG" Model Kids',
                'slug' => 'haljina-za-devojcice-mdg-model-kids',
                'details' => NULL,
                'price' => 780,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 46,
                'manufacturer_id' => 2,
                'image' => 'products\\August2020\\DVG3ImYgc4xLOvJ1dN2R.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 14:17:05',
                'updated_at' => '2020-08-25 14:17:05',
            ),
            29 => 
            array (
                'id' => 57,
                'name' => 'Haljina "Keep the wild in you" Kid Star',
                'slug' => 'haljina-keep-the-wild-in-you-kid-star',
                'details' => NULL,
                'price' => 1050,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 46,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\znjuKmKUP8FJlDLOxqQ3.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 14:18:47',
                'updated_at' => '2020-08-25 14:18:47',
            ),
            30 => 
            array (
                'id' => 58,
                'name' => 'Haljina za devojčice sa kapuljačom Kid Star',
                'slug' => 'haljina-za-devojcice-sa-kapuljacom-kid-star',
                'details' => NULL,
                'price' => 1550,
                'description' => NULL,
                'quantity' => 6,
                'category_id' => 46,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\4QclMJ1QV7wb9sA7xu8T.jpg',
                'images' => '["products\\\\August2020\\\\qD8IcvdYpfFxnIGPMI4p.jpg"]',
                'created_at' => '2020-08-25 14:20:40',
                'updated_at' => '2020-08-25 14:20:40',
            ),
            31 => 
            array (
                'id' => 59,
                'name' => 'Suknja za devojčice Model Kids',
                'slug' => 'suknja-za-devojcice-model-kids',
                'details' => NULL,
                'price' => 580,
                'description' => NULL,
                'quantity' => 8,
                'category_id' => 47,
                'manufacturer_id' => 2,
                'image' => 'products\\August2020\\bfvYHcc1N38PU4sHZfzE.jpg',
                'images' => '["products\\\\August2020\\\\Fp8vH85i4ME1lFbvKF32.jpg"]',
                'created_at' => '2020-08-25 14:23:47',
                'updated_at' => '2020-08-25 14:23:47',
            ),
            32 => 
            array (
                'id' => 60,
                'name' => 'Trenerka za devojčice sa kapuljačom "Panter"',
                'slug' => 'trenerka-za-devojcice-sa-kapuljacom-panter',
                'details' => NULL,
                'price' => 2590,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 50,
                'manufacturer_id' => 3,
                'image' => 'products\\August2020\\FyUXk5jIfPJh9k4KWXbU.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 14:25:28',
                'updated_at' => '2020-08-25 14:25:28',
            ),
            33 => 
            array (
                'id' => 61,
                'name' => 'Trenerka za devojčice "Love" Panter',
                'slug' => 'trenerka-za-devojcice-love-panter',
                'details' => NULL,
                'price' => 2490,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 50,
                'manufacturer_id' => 3,
                'image' => 'products\\August2020\\Ak2R4rlPgSqyjSrWmzZv.jpg',
                'images' => '["products\\\\August2020\\\\7lHQhPKaIG0q3gO8oGXt.jpg"]',
                'created_at' => '2020-08-25 15:00:13',
                'updated_at' => '2020-08-25 15:00:13',
            ),
            34 => 
            array (
                'id' => 62,
                'name' => 'Trenerka za devojčice sa kapuljačom "Panter" - siva',
                'slug' => 'trenerka-za-devojcice-sa-kapuljacom-panter-siva',
                'details' => NULL,
                'price' => 2990,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 50,
                'manufacturer_id' => 3,
                'image' => 'products\\August2020\\RGFMYqY7HmbiykKdtI8Q.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 15:01:43',
                'updated_at' => '2020-08-25 15:01:43',
            ),
            35 => 
            array (
                'id' => 63,
                'name' => 'Trenerka za devojčice "Big Kiss" Panter',
                'slug' => 'trenerka-za-devojcice-big-kiss-panter',
                'details' => NULL,
                'price' => 2990,
                'description' => NULL,
                'quantity' => 4,
                'category_id' => 50,
                'manufacturer_id' => 3,
                'image' => 'products\\August2020\\gbkHwkIlCz40O8GlUCCd.jpg',
                'images' => '["products\\\\August2020\\\\BEo84PNE0mRh4xC7iCAd.jpg"]',
                'created_at' => '2020-08-25 15:03:34',
                'updated_at' => '2020-08-25 15:03:34',
            ),
        ));
        
        
    }
}