<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 27,
                'name' => 'Ženska haljina Sloga MB',
                'slug' => 'zenska-haljina-sloga-mb',
                'details' => NULL,
                'price' => 1450,
                'description' => NULL,
                'quantity' => 0,
                'category_id' => 81,
                'manufacturer_id' => 6,
                'image' => 'products\\August2020\\7dxvV6LbV9rF13OMd6YL.jpg',
                'images' => '["products\\\\August2020\\\\VIi2utj4bVPCTgM35gYX.jpg","products\\\\August2020\\\\yXv3V0jYrttkLSwKWslv.jpg"]',
                'created_at' => '2020-08-20 11:34:58',
                'updated_at' => '2020-09-02 19:44:51',
            ),
            1 => 
            array (
                'id' => 28,
                'name' => 'Cool Boy duks',
                'slug' => 'cool-boy-duks',
                'details' => NULL,
                'price' => 750,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 15,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\vb3cJVoxzQstYSH0j02d.jpg',
                'images' => '["products\\\\August2020\\\\8zFLJ5rmamZzJLFuPzUl.jpg","products\\\\August2020\\\\JEJcQGfrA9c6MUguIdeR.jpg","products\\\\August2020\\\\AyLTS2eRyl1x75tzId5l.jpg"]',
                'created_at' => '2020-08-20 11:47:23',
                'updated_at' => '2020-08-20 14:23:27',
            ),
            2 => 
            array (
                'id' => 29,
                'name' => 'Duks za devojčice Kid Star',
                'slug' => 'duks-za-devojcice-kid-star',
                'details' => NULL,
                'price' => 890,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 53,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\BcqHY9wUCtnZLMxfXzPX.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 11:50:58',
                'updated_at' => '2020-08-20 14:23:01',
            ),
            3 => 
            array (
                'id' => 30,
                'name' => 'Duks Urban Style',
                'slug' => 'duks-urban-style',
                'details' => NULL,
                'price' => 1390,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 29,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\5B9WsQYj9L5IFhqg0JPz.jpg',
                'images' => '["products\\\\August2020\\\\ETBMIXWALoaT0HadriLU.jpg","products\\\\August2020\\\\kT6ZuFqfJrmlL7E24n2H.jpg"]',
                'created_at' => '2020-08-20 11:54:01',
                'updated_at' => '2020-08-20 14:21:17',
            ),
            4 => 
            array (
                'id' => 31,
                'name' => 'Majica "Made with love"',
                'slug' => 'majica-made-with-love',
                'details' => NULL,
                'price' => 1390,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 45,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\LxvzFxdiJc9iXbaX5Iy7.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 12:00:12',
                'updated_at' => '2020-08-20 14:22:11',
            ),
            5 => 
            array (
                'id' => 32,
                'name' => 'Duks "1976"',
                'slug' => 'duks-1976',
                'details' => NULL,
                'price' => 990,
                'description' => NULL,
                'quantity' => 4,
                'category_id' => 29,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\e5WHX4FaKq3bEkdtRm9p.jpg',
                'images' => '["products\\\\August2020\\\\LOs0CJq5t00hZ4ioSTkz.jpg","products\\\\August2020\\\\bp70VkmhHjNuhJe4C1wR.jpg"]',
                'created_at' => '2020-08-20 12:02:13',
                'updated_at' => '2020-08-20 14:20:48',
            ),
            6 => 
            array (
                'id' => 34,
                'name' => 'Duks za devojčice "Simplify"',
                'slug' => 'duks-za-devojcice-simplify',
                'details' => NULL,
                'price' => 1190,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 53,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\aAqKMQosVw5k8evypBJt.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 12:04:48',
                'updated_at' => '2020-08-20 14:20:26',
            ),
            7 => 
            array (
                'id' => 35,
                'name' => 'Haljinica za bebe "Love"',
                'slug' => 'haljinica-za-bebe-love',
                'details' => NULL,
                'price' => 1050,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 9,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\rQYPDsdkUvNPMtONsNiG.jpg',
                'images' => '["products\\\\August2020\\\\JQOSKuOwk4b9UGWMcHtp.jpg","products\\\\August2020\\\\XCehS96Ek8lIFDD46Lus.jpg"]',
                'created_at' => '2020-08-20 12:08:27',
                'updated_at' => '2020-08-20 12:12:03',
            ),
            8 => 
            array (
                'id' => 36,
                'name' => 'Zeka za devojčice "Jednorog"',
                'slug' => 'zeka-za-devojcice-jednorog',
                'details' => NULL,
                'price' => 570,
                'description' => NULL,
                'quantity' => 0,
                'category_id' => 4,
                'manufacturer_id' => 2,
                'image' => 'products\\August2020\\dVF0l1an2qsVm65nFpYz.jpg',
                'images' => '["products\\\\August2020\\\\5oZFLQYhOBO5OIfVkV3c.jpg","products\\\\August2020\\\\ZC3qW7hyYmGNIVL5ZF2p.jpg","products\\\\August2020\\\\KpwMxETM7Z8mWLeyGUOG.jpg","products\\\\August2020\\\\iw6Ji8hvKzdijDMT6MZF.jpg"]',
                'created_at' => '2020-08-20 12:17:40',
                'updated_at' => '2020-09-02 19:44:18',
            ),
            9 => 
            array (
                'id' => 37,
                'name' => 'Zeka za devojčice "Ooh Daris"',
                'slug' => 'zeka-za-devojcice-ooh-daris',
                'details' => NULL,
                'price' => 530,
                'description' => NULL,
                'quantity' => 7,
                'category_id' => 4,
                'manufacturer_id' => 2,
                'image' => 'products\\August2020\\XBm4aH0PIURu2dyCcygh.jpg',
                'images' => '["products\\\\August2020\\\\G7i80RuxesMgI9E2mreP.jpg","products\\\\August2020\\\\lj5Q1WBX9yatclhp8fKQ.jpg","products\\\\August2020\\\\bZsT365iZCTXPf8BYrxk.jpg"]',
                'created_at' => '2020-08-20 12:21:22',
                'updated_at' => '2020-08-20 12:21:22',
            ),
            10 => 
            array (
                'id' => 38,
                'name' => 'Džemper za dečake "Bambino"',
                'slug' => 'dzemper-za-decake-bambino',
                'details' => NULL,
                'price' => 1190,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 30,
                'manufacturer_id' => 1,
                'image' => 'products\\August2020\\UzBRtY9vAH9rT7wK0RXc.jpg',
                'images' => '["products\\\\August2020\\\\709bFpjxTVY9YLzcZJFM.jpg","products\\\\August2020\\\\p0T5Mq9KchJ2J4RIvjtA.jpg","products\\\\August2020\\\\7ab5YJrIZdJN3Ng81VqD.jpg"]',
                'created_at' => '2020-08-20 12:25:59',
                'updated_at' => '2020-08-20 14:19:48',
            ),
            11 => 
            array (
                'id' => 39,
                'name' => 'Trenerka za devojčice "Inpsiration"',
                'slug' => 'trenerka-za-devojcice-inpsiration',
                'details' => NULL,
                'price' => 2190,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 50,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\ZjeQwrgK4EoB0aOHOoLi.jpg',
                'images' => '["products\\\\August2020\\\\RP0G4OYUPjd4rIANGd2v.jpg","products\\\\August2020\\\\UrVT2E331IpUHUmkHZSD.jpg"]',
                'created_at' => '2020-08-20 13:29:24',
                'updated_at' => '2020-08-20 14:19:29',
            ),
            12 => 
            array (
                'id' => 40,
                'name' => 'Tregerice za bebe Bambino',
                'slug' => 'tregerice-za-bebe-bambino',
                'details' => NULL,
                'price' => 1700,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 16,
                'manufacturer_id' => 1,
                'image' => 'products\\August2020\\C0WFsmcxdwjCBHONlXVV.jpg',
                'images' => '["products\\\\August2020\\\\J15P8frKOYwfRAzSljVq.jpg","products\\\\August2020\\\\W8qy0Ugi3GDwZQlsGSz3.jpg"]',
                'created_at' => '2020-08-20 13:38:35',
                'updated_at' => '2020-08-20 13:39:12',
            ),
            13 => 
            array (
                'id' => 41,
                'name' => 'Posteljina za bebe Hajdi',
                'slug' => 'posteljina-za-bebe-hajdi',
                'details' => NULL,
                'price' => 4200,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 92,
                'manufacturer_id' => 7,
                'image' => 'products\\August2020\\sMLBfPwzQ5R8D0S4OApu.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 13:41:23',
                'updated_at' => '2020-08-20 14:19:10',
            ),
            14 => 
            array (
                'id' => 42,
                'name' => 'Farmerice za devojčice Bambino',
                'slug' => 'farmerice-za-devojcice-bambino',
                'details' => NULL,
                'price' => 1800,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 49,
                'manufacturer_id' => 1,
                'image' => 'products\\August2020\\QtYwCJ1BYMtZ2hen71Cj.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 13:44:47',
                'updated_at' => '2020-08-20 14:18:47',
            ),
            15 => 
            array (
                'id' => 43,
                'name' => 'Farmerke za dečake Bambino',
                'slug' => 'farmerke-za-decake-bambino',
                'details' => NULL,
                'price' => 1700,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 33,
                'manufacturer_id' => 1,
                'image' => 'products\\August2020\\i3k1daZ5axfmnSZK00V3.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 13:46:18',
                'updated_at' => '2020-08-20 13:46:18',
            ),
            16 => 
            array (
                'id' => 44,
                'name' => 'Ćebe za bebe "Meda" - Radović',
                'slug' => 'cebe-za-bebe-meda-radovic',
                'details' => NULL,
                'price' => 1200,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 92,
                'manufacturer_id' => 4,
                'image' => 'products\\August2020\\yWuqiHOgvkc9xNUkh2lk.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 13:48:11',
                'updated_at' => '2020-08-20 14:18:21',
            ),
            17 => 
            array (
                'id' => 45,
                'name' => 'Ćebe za bebe "Baby bunny" - Radović',
                'slug' => 'cebe-za-bebe-baby-bunny-radovic',
                'details' => NULL,
                'price' => 1300,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 92,
                'manufacturer_id' => 4,
                'image' => 'products\\August2020\\3BuSpfLG9JgKeR6vwiUy.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 13:50:07',
                'updated_at' => '2020-08-20 14:18:04',
            ),
            18 => 
            array (
                'id' => 46,
                'name' => 'Ćebe za bebe "Slonče" Hajdi',
                'slug' => 'cebe-za-bebe-slonce-hajdi',
                'details' => NULL,
                'price' => 1060,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 92,
                'manufacturer_id' => 7,
                'image' => 'products\\August2020\\3ZDk0JITJ76YRf9IOiRL.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 13:52:03',
                'updated_at' => '2020-08-20 14:17:49',
            ),
            19 => 
            array (
                'id' => 47,
                'name' => 'Bade mantil za devojčice Hajdi',
                'slug' => 'bade-mantil-za-devojcice-hajdi',
                'details' => NULL,
                'price' => 1550,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 61,
                'manufacturer_id' => 7,
                'image' => 'products\\August2020\\YDlQXX29lusSRieQCweF.jpg',
                'images' => NULL,
                'created_at' => '2020-08-20 13:55:07',
                'updated_at' => '2020-08-20 13:58:16',
            ),
            20 => 
            array (
                'id' => 48,
                'name' => 'Bade mantil za dečake Hajdi',
                'slug' => 'bade-mantil-za-decake-hajdi',
                'details' => NULL,
                'price' => 1550,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 42,
                'manufacturer_id' => 7,
                'image' => 'products\\August2020\\jVHaBUmVOiNa3TQ0LBhQ.jpg',
                'images' => '["products\\\\August2020\\\\CjC8XpC7vSWC0amcE4bl.jpg","products\\\\August2020\\\\RxwppNAmsprYPrBlcW0w.jpg"]',
                'created_at' => '2020-08-20 13:59:56',
                'updated_at' => '2020-08-20 13:59:56',
            ),
            21 => 
            array (
                'id' => 49,
                'name' => 'Haljina "Just Love Sun"',
                'slug' => 'haljina-just-love-sun',
                'details' => NULL,
                'price' => 780,
                'description' => NULL,
                'quantity' => 0,
                'category_id' => 46,
                'manufacturer_id' => 2,
                'image' => 'products\\August2020\\WQO9StlO6Hjo5XIXli3B.jpg',
                'images' => '["products\\\\August2020\\\\OQiwVbXanzatCTc2MqlF.jpg","products\\\\August2020\\\\tOnAKIy5fkj3tkR10KCE.jpg"]',
                'created_at' => '2020-08-25 13:57:22',
                'updated_at' => '2020-09-02 19:43:22',
            ),
            22 => 
            array (
                'id' => 50,
                'name' => 'Haljina "I woke up like this"',
                'slug' => 'haljina-i-woke-up-like-this',
                'details' => NULL,
                'price' => 1050,
                'description' => NULL,
                'quantity' => 0,
                'category_id' => 46,
                'manufacturer_id' => 1,
                'image' => 'products\\August2020\\KnZWvuvfethV2BNZFagk.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 14:01:38',
                'updated_at' => '2020-09-02 19:42:55',
            ),
            23 => 
            array (
                'id' => 51,
                'name' => 'Cvetna haljina za devojčice Model kids',
                'slug' => 'cvetna-haljina-za-devojcice-model-kids',
                'details' => NULL,
                'price' => 550,
                'description' => NULL,
                'quantity' => 0,
                'category_id' => 46,
                'manufacturer_id' => 2,
                'image' => 'products\\August2020\\YW0ZbxjBBXCA6dBhUCTX.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 14:04:32',
                'updated_at' => '2020-09-02 19:40:20',
            ),
            24 => 
            array (
                'id' => 52,
                'name' => 'Haljina za devojčice "Be Lovely" Model Kids',
                'slug' => 'haljina-za-devojcice-be-lovely-model-kids',
                'details' => NULL,
                'price' => 780,
                'description' => NULL,
                'quantity' => -1,
                'category_id' => 46,
                'manufacturer_id' => 2,
                'image' => 'products\\August2020\\Jnebu0lLgAeTDznKiF9b.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 14:07:00',
                'updated_at' => '2020-09-02 19:40:58',
            ),
            25 => 
            array (
                'id' => 53,
                'name' => 'Haljina za devojčice "Sailing Blue" Bambino',
                'slug' => 'haljina-za-devojcice-sailing-blue-bambino',
                'details' => NULL,
                'price' => 950,
                'description' => NULL,
                'quantity' => 0,
                'category_id' => 46,
                'manufacturer_id' => 1,
                'image' => 'products\\August2020\\fjBB3Q3VHkfnrE0yqqg2.jpg',
                'images' => '["products\\\\August2020\\\\Wjaxs1SCAFRNpUZ3c3E7.jpg","products\\\\August2020\\\\yCgQXngpEG2iSHj7NkfP.jpg"]',
                'created_at' => '2020-08-25 14:10:03',
                'updated_at' => '2020-09-02 19:39:54',
            ),
            26 => 
            array (
                'id' => 54,
                'name' => 'Haljina za devojčice "Višnje" Panter',
                'slug' => 'haljina-za-devojcice-visnje-panter',
                'details' => NULL,
                'price' => 1200,
                'description' => NULL,
                'quantity' => 0,
                'category_id' => 46,
                'manufacturer_id' => 3,
                'image' => 'products\\August2020\\DMt6JXtHJG9E1eR7KLhM.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 14:13:22',
                'updated_at' => '2020-09-02 19:39:27',
            ),
            27 => 
            array (
                'id' => 55,
                'name' => 'Haljina za devočice "Srca" Panter',
                'slug' => 'haljina-za-devocice-srca-panter',
                'details' => NULL,
                'price' => 1200,
                'description' => NULL,
                'quantity' => 0,
                'category_id' => 46,
                'manufacturer_id' => 3,
                'image' => 'products\\August2020\\SBnptiLsKFT9402SWvUy.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 14:14:13',
                'updated_at' => '2020-09-02 19:38:57',
            ),
            28 => 
            array (
                'id' => 56,
                'name' => 'Haljina za devojčice "MDG" Model Kids',
                'slug' => 'haljina-za-devojcice-mdg-model-kids',
                'details' => NULL,
                'price' => 780,
                'description' => NULL,
                'quantity' => 0,
                'category_id' => 46,
                'manufacturer_id' => 2,
                'image' => 'products\\August2020\\DVG3ImYgc4xLOvJ1dN2R.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 14:17:05',
                'updated_at' => '2020-09-02 19:35:14',
            ),
            29 => 
            array (
                'id' => 57,
                'name' => 'Haljina "Keep the wild in you" Kid Star',
                'slug' => 'haljina-keep-the-wild-in-you-kid-star',
                'details' => NULL,
                'price' => 1050,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 46,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\znjuKmKUP8FJlDLOxqQ3.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 14:18:47',
                'updated_at' => '2020-08-25 14:18:47',
            ),
            30 => 
            array (
                'id' => 58,
                'name' => 'Haljina za devojčice sa kapuljačom Kid Star',
                'slug' => 'haljina-za-devojcice-sa-kapuljacom-kid-star',
                'details' => NULL,
                'price' => 1550,
                'description' => NULL,
                'quantity' => 6,
                'category_id' => 46,
                'manufacturer_id' => 5,
                'image' => 'products\\August2020\\4QclMJ1QV7wb9sA7xu8T.jpg',
                'images' => '["products\\\\August2020\\\\qD8IcvdYpfFxnIGPMI4p.jpg"]',
                'created_at' => '2020-08-25 14:20:40',
                'updated_at' => '2020-08-25 14:20:40',
            ),
            31 => 
            array (
                'id' => 59,
                'name' => 'Suknja za devojčice Model Kids',
                'slug' => 'suknja-za-devojcice-model-kids',
                'details' => NULL,
                'price' => 580,
                'description' => NULL,
                'quantity' => 8,
                'category_id' => 47,
                'manufacturer_id' => 2,
                'image' => 'products\\August2020\\bfvYHcc1N38PU4sHZfzE.jpg',
                'images' => '["products\\\\August2020\\\\Fp8vH85i4ME1lFbvKF32.jpg"]',
                'created_at' => '2020-08-25 14:23:47',
                'updated_at' => '2020-08-25 14:23:47',
            ),
            32 => 
            array (
                'id' => 60,
                'name' => 'Trenerka za devojčice sa kapuljačom "Panter"',
                'slug' => 'trenerka-za-devojcice-sa-kapuljacom-panter',
                'details' => NULL,
                'price' => 2590,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 50,
                'manufacturer_id' => 3,
                'image' => 'products\\August2020\\FyUXk5jIfPJh9k4KWXbU.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 14:25:28',
                'updated_at' => '2020-08-25 14:25:28',
            ),
            33 => 
            array (
                'id' => 61,
                'name' => 'Trenerka za devojčice "Love" Panter',
                'slug' => 'trenerka-za-devojcice-love-panter',
                'details' => NULL,
                'price' => 2490,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 50,
                'manufacturer_id' => 3,
                'image' => 'products\\August2020\\Ak2R4rlPgSqyjSrWmzZv.jpg',
                'images' => '["products\\\\August2020\\\\7lHQhPKaIG0q3gO8oGXt.jpg"]',
                'created_at' => '2020-08-25 15:00:13',
                'updated_at' => '2020-08-25 15:00:13',
            ),
            34 => 
            array (
                'id' => 62,
                'name' => 'Trenerka za devojčice sa kapuljačom "Panter" - siva',
                'slug' => 'trenerka-za-devojcice-sa-kapuljacom-panter-siva',
                'details' => NULL,
                'price' => 2990,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 50,
                'manufacturer_id' => 3,
                'image' => 'products\\August2020\\RGFMYqY7HmbiykKdtI8Q.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 15:01:43',
                'updated_at' => '2020-08-25 15:01:43',
            ),
            35 => 
            array (
                'id' => 63,
                'name' => 'Trenerka za devojčice "Big Kiss" Panter',
                'slug' => 'trenerka-za-devojcice-big-kiss-panter',
                'details' => NULL,
                'price' => 2990,
                'description' => NULL,
                'quantity' => 4,
                'category_id' => 50,
                'manufacturer_id' => 3,
                'image' => 'products\\August2020\\gbkHwkIlCz40O8GlUCCd.jpg',
                'images' => '["products\\\\August2020\\\\BEo84PNE0mRh4xC7iCAd.jpg"]',
                'created_at' => '2020-08-25 15:03:34',
                'updated_at' => '2020-08-25 15:03:34',
            ),
            36 => 
            array (
                'id' => 64,
                'name' => 'Kupko za bebe',
                'slug' => 'kupko-za-bebe',
                'details' => 'frotir',
                'price' => 540,
                'description' => NULL,
                'quantity' => 4,
                'category_id' => 18,
                'manufacturer_id' => 4,
                'image' => 'products\\August2020\\YszfqH4ngxnMV3FgdNd6.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 19:00:39',
                'updated_at' => '2020-08-25 19:00:39',
            ),
            37 => 
            array (
                'id' => 65,
                'name' => 'Trenerka Sport',
                'slug' => 'trenerka-sport',
                'details' => '100% pamuk',
                'price' => 2490,
                'description' => '<p>Trenerka za dečake</p>',
                'quantity' => 1,
                'category_id' => 31,
                'manufacturer_id' => 3,
                'image' => 'products\\August2020\\ANjRXMy9Mu8M66YusEkp.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 19:05:37',
                'updated_at' => '2020-08-25 19:05:37',
            ),
            38 => 
            array (
                'id' => 66,
                'name' => 'Trenerka Super',
                'slug' => 'trenerka-super',
                'details' => NULL,
                'price' => 2990,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 31,
                'manufacturer_id' => 3,
                'image' => 'products\\August2020\\Fxd2MNSiZBYLcTgq5T0f.jpg',
                'images' => '["products\\\\August2020\\\\TEUH5SupiNgTPMJz45Vy.jpg","products\\\\August2020\\\\WGS9OQQPpsbjQmI69cQN.jpg"]',
                'created_at' => '2020-08-25 19:27:04',
                'updated_at' => '2020-08-25 19:27:04',
            ),
            39 => 
            array (
                'id' => 67,
                'name' => 'Trenerka komplet Original',
                'slug' => 'trenerka-komplet-original',
                'details' => '100 % pamuk',
                'price' => 3490,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 31,
                'manufacturer_id' => 3,
                'image' => 'products\\August2020\\xvFeGwf2eSj5VzSIeRhi.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 19:29:19',
                'updated_at' => '2020-08-25 19:29:19',
            ),
            40 => 
            array (
                'id' => 68,
                'name' => 'Košulja za dečake sa natpisom',
                'slug' => 'kosulja-za-decake-sa-natpisom',
                'details' => '100% pamuk',
                'price' => 1500,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 95,
                'manufacturer_id' => 1,
                'image' => 'products\\August2020\\JZgcZl0LXdhygPYMPtd3.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 19:36:26',
                'updated_at' => '2020-08-25 19:36:26',
            ),
            41 => 
            array (
                'id' => 69,
                'name' => 'Košulja za dečake bela',
                'slug' => 'kosulja-za-decake-bela',
                'details' => NULL,
                'price' => 1500,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 95,
                'manufacturer_id' => 1,
                'image' => 'products\\August2020\\aoldXWqqDD54KhmWekdG.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 19:38:06',
                'updated_at' => '2020-08-25 19:38:06',
            ),
            42 => 
            array (
                'id' => 70,
                'name' => 'Košulja ruska kragna',
                'slug' => 'kosulja-ruska-kragna',
                'details' => NULL,
                'price' => 1500,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 95,
                'manufacturer_id' => 1,
                'image' => 'products\\August2020\\vKFxGyuYbd0RB69BFyy4.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 20:31:52',
                'updated_at' => '2020-08-25 20:32:12',
            ),
            43 => 
            array (
                'id' => 71,
                'name' => 'Dećaci košulja prugice',
                'slug' => 'decaci-kosulja-prugice',
                'details' => NULL,
                'price' => 1500,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 95,
                'manufacturer_id' => 1,
                'image' => 'products\\August2020\\kr2FmU7e9LrdEIvttiGz.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 20:33:22',
                'updated_at' => '2020-08-25 22:03:41',
            ),
            44 => 
            array (
                'id' => 72,
                'name' => 'Pidžama za devojčice CDM',
                'slug' => 'pidzama-za-devojcice-cdm',
                'details' => NULL,
                'price' => 930,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 57,
                'manufacturer_id' => 8,
                'image' => 'products\\August2020\\z2VIJozpBaiIWQgGRpEi.jpg',
                'images' => NULL,
                'created_at' => '2020-08-25 20:45:10',
                'updated_at' => '2020-08-25 20:45:10',
            ),
            45 => 
            array (
                'id' => 73,
                'name' => 'Pidžama za devojčice Hello Spring',
                'slug' => 'pidzama-za-devojcice-hello-spring',
                'details' => NULL,
                'price' => 1100,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 57,
                'manufacturer_id' => 9,
                'image' => 'products\\August2020\\MzMvT2LT7sVE0ZxQOzq2.jpg',
                'images' => NULL,
                'created_at' => '2020-08-28 11:55:33',
                'updated_at' => '2020-08-28 11:55:33',
            ),
            46 => 
            array (
                'id' => 74,
                'name' => 'Pidžama za devojčice Jasmil Magic',
                'slug' => 'pidzama-za-devojcice-jasmil-magic',
                'details' => NULL,
                'price' => 1220,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 57,
                'manufacturer_id' => 10,
                'image' => 'products\\August2020\\iC4VzzSN7FDYV1YAE7rb.jpg',
                'images' => NULL,
                'created_at' => '2020-08-28 11:57:31',
                'updated_at' => '2020-08-28 11:57:31',
            ),
            47 => 
            array (
                'id' => 75,
                'name' => 'Pidžama za devojčice Little princess',
                'slug' => 'pidzama-za-devojcice-little-princess',
                'details' => NULL,
                'price' => 930,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 57,
                'manufacturer_id' => 11,
                'image' => 'products\\August2020\\5GgyVzN7U0o1mf4HiTcE.jpg',
                'images' => NULL,
                'created_at' => '2020-08-28 12:00:06',
                'updated_at' => '2020-08-28 12:00:06',
            ),
            48 => 
            array (
                'id' => 76,
                'name' => 'Pidžama za devojčice Lotos Born to be free',
                'slug' => 'pidzama-za-devojcice-lotos-born-to-be-free',
                'details' => NULL,
                'price' => 1000,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 57,
                'manufacturer_id' => 12,
                'image' => 'products\\August2020\\YLh0TuGgKXsjkzCY6V5g.jpg',
                'images' => NULL,
                'created_at' => '2020-08-28 12:01:49',
                'updated_at' => '2020-08-28 12:01:49',
            ),
            49 => 
            array (
                'id' => 77,
                'name' => 'Pidžama za dečake Amibo',
                'slug' => 'pidzama-za-decake-amibo',
                'details' => NULL,
                'price' => 1600,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 41,
                'manufacturer_id' => 12,
                'image' => 'products\\August2020\\AhYc9iiwSd2t9zCSqbzF.jpg',
                'images' => NULL,
                'created_at' => '2020-08-28 12:03:25',
                'updated_at' => '2020-08-28 12:03:25',
            ),
            50 => 
            array (
                'id' => 78,
                'name' => 'Pidžama za dečake New York',
                'slug' => 'pidzama-za-decake-new-york',
                'details' => NULL,
                'price' => 1220,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 41,
                'manufacturer_id' => 12,
                'image' => 'products\\August2020\\ggmcOxJeOmyko9qYRkgA.jpg',
                'images' => NULL,
                'created_at' => '2020-08-28 12:05:08',
                'updated_at' => '2020-08-28 12:05:08',
            ),
            51 => 
            array (
                'id' => 79,
                'name' => 'Pidžama za dečake Jasmil Back to school',
                'slug' => 'pidzama-za-decake-jasmil-back-to-school',
                'details' => NULL,
                'price' => 1900,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 41,
                'manufacturer_id' => 10,
                'image' => 'products\\August2020\\HG9GOgQAunzciNxL908X.jpg',
                'images' => NULL,
                'created_at' => '2020-08-28 12:07:01',
                'updated_at' => '2020-08-28 12:07:01',
            ),
            52 => 
            array (
                'id' => 80,
                'name' => 'Ženska spavaćica na dugmiće Lotos',
                'slug' => 'zenska-spavacica-na-dugmice-lotos',
                'details' => NULL,
                'price' => 1420,
                'description' => NULL,
                'quantity' => 4,
                'category_id' => 96,
                'manufacturer_id' => 12,
                'image' => 'products\\August2020\\VHT07W5vFHv8ScX4lovF.jpg',
                'images' => '["products\\\\August2020\\\\otDzAIs53p85XHl1xWik.jpg","products\\\\August2020\\\\EeLWm4YGODtOoSTmCKAK.jpg"]',
                'created_at' => '2020-08-28 12:10:47',
                'updated_at' => '2020-08-28 12:10:47',
            ),
            53 => 
            array (
                'id' => 81,
                'name' => 'Ženska spavaćica bez rukava Boa',
                'slug' => 'zenska-spavacica-bez-rukava-boa',
                'details' => NULL,
                'price' => 1300,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 96,
                'manufacturer_id' => 13,
                'image' => 'products\\August2020\\oZ95iLUfvJXTffm7lMUc.jpg',
                'images' => NULL,
                'created_at' => '2020-08-28 12:15:46',
                'updated_at' => '2020-08-28 12:16:12',
            ),
            54 => 
            array (
                'id' => 82,
                'name' => 'Ženska pidžama Amibo',
                'slug' => 'zenska-pidzama-amibo',
                'details' => '100% pamuk',
                'price' => 2400,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 88,
                'manufacturer_id' => 14,
                'image' => 'products\\September2020\\SzlBubdlHvu38Sf0Y9kG.jpg',
                'images' => NULL,
                'created_at' => '2020-09-02 20:03:48',
                'updated_at' => '2020-09-02 20:05:17',
            ),
            55 => 
            array (
                'id' => 83,
                'name' => 'Ženska pidžama Amibo Irvas',
                'slug' => 'zenska-pidzama-amibo-irvas',
                'details' => '95% pamuk, 5% elastan',
                'price' => 2500,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 88,
                'manufacturer_id' => 14,
                'image' => 'products\\September2020\\KT7tpbUe1QSYa1y9yrEL.jpg',
                'images' => NULL,
                'created_at' => '2020-09-02 20:07:18',
                'updated_at' => '2020-09-02 20:07:18',
            ),
            56 => 
            array (
                'id' => 85,
                'name' => 'Ženska pidžama Zima',
                'slug' => 'zenska-pidzama-zima',
                'details' => '95% pamuk, 5% elastan',
                'price' => 2500,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 88,
                'manufacturer_id' => 14,
                'image' => 'products\\September2020\\RlyZHNHIeGbjHXQreB9T.jpg',
                'images' => '["products\\\\September2020\\\\TTNiWLsbLxFhKbGJ7Mno.jpg","products\\\\September2020\\\\etW2R8vT8WrhVmT1ZoT9.jpg","products\\\\September2020\\\\tDiRgQyVReNF2GiVrP8v.jpg"]',
                'created_at' => '2020-09-02 20:11:22',
                'updated_at' => '2020-09-02 20:11:22',
            ),
            57 => 
            array (
                'id' => 86,
                'name' => 'Muška majica kratki rukav',
                'slug' => 'muska-majica-kratki-rukav',
                'details' => '95%pamuk 5%elastan',
                'price' => 1400,
                'description' => NULL,
                'quantity' => 10,
                'category_id' => 65,
                'manufacturer_id' => 15,
                'image' => 'products\\September2020\\f9T7Lg17mPYWQjs44tC7.jpg',
                'images' => '["products\\\\September2020\\\\kGvInbNYVZLFlaFvYdTO.jpg","products\\\\September2020\\\\ahVaXUj70NAhkmsYpnsH.jpg","products\\\\September2020\\\\lBZejXG89Qfe1jNnHb7x.jpg"]',
                'created_at' => '2020-09-02 20:16:07',
                'updated_at' => '2020-09-02 20:17:42',
            ),
            58 => 
            array (
                'id' => 87,
                'name' => 'Muška bodz majica nestruirana Ewox',
                'slug' => 'muska-bodz-majica-nestruirana-ewox',
                'details' => NULL,
                'price' => 990,
                'description' => NULL,
                'quantity' => 4,
                'category_id' => 65,
                'manufacturer_id' => 16,
                'image' => 'products\\September2020\\512FwFl2FMJnfOYQ8oYZ.jpg',
                'images' => NULL,
                'created_at' => '2020-09-02 20:21:00',
                'updated_at' => '2020-09-02 20:21:00',
            ),
            59 => 
            array (
                'id' => 88,
                'name' => 'Muška bodz majica struirana Ewox',
                'slug' => 'muska-bodz-majica-struirana-ewox',
                'details' => NULL,
                'price' => 1100,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 65,
                'manufacturer_id' => 16,
                'image' => 'products\\September2020\\iaVNDxwNPWGEL1YXaLpA.jpg',
                'images' => NULL,
                'created_at' => '2020-09-02 20:23:08',
                'updated_at' => '2020-09-02 20:23:08',
            ),
            60 => 
            array (
                'id' => 89,
                'name' => 'Ženskadonji deo pidžame Sloga',
                'slug' => 'zenskadonji-deo-pidzame-sloga',
                'details' => NULL,
                'price' => 1050,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 88,
                'manufacturer_id' => 6,
                'image' => 'products\\September2020\\4Vlma9L3jvzlBIkvIcWS.jpg',
                'images' => '["products\\\\September2020\\\\h4bpzdkUt0X7Er7H1QMU.jpg","products\\\\September2020\\\\aHQWUEdrUo3o0rYSWhWa.jpg"]',
                'created_at' => '2020-09-02 20:26:16',
                'updated_at' => '2020-09-02 20:26:16',
            ),
            61 => 
            array (
                'id' => 90,
                'name' => 'Muška potkošulja',
                'slug' => 'muska-potkosulja',
                'details' => NULL,
                'price' => 315,
                'description' => NULL,
                'quantity' => 20,
                'category_id' => 70,
                'manufacturer_id' => 17,
                'image' => 'products\\September2020\\Dp1W2mOKa4MrvOHqu2jK.jpg',
                'images' => '["products\\\\September2020\\\\yowJ85ocwembsIZ650yw.jpg","products\\\\September2020\\\\1tWmUJpDQikDSaf16QjI.jpg","products\\\\September2020\\\\ZgKPMaZHEAFKCxJ4aFvm.jpg"]',
                'created_at' => '2020-09-02 20:42:41',
                'updated_at' => '2020-09-02 20:43:32',
            ),
            62 => 
            array (
                'id' => 91,
                'name' => 'Peškir 70x140',
                'slug' => 'peskir-70x140',
                'details' => NULL,
                'price' => 450,
                'description' => NULL,
                'quantity' => 10,
                'category_id' => 91,
                'manufacturer_id' => 18,
                'image' => 'products\\September2020\\cfLJLy58qcJfKeLKRvXL.jpg',
                'images' => NULL,
                'created_at' => '2020-09-02 21:12:28',
                'updated_at' => '2020-09-02 21:12:28',
            ),
            63 => 
            array (
                'id' => 92,
                'name' => 'Peškir 50x100',
                'slug' => 'peskir-50x100',
                'details' => NULL,
                'price' => 220,
                'description' => NULL,
                'quantity' => 10,
                'category_id' => 91,
                'manufacturer_id' => 18,
                'image' => 'products\\September2020\\PmKjA3X34pGGTME8korV.jpg',
                'images' => '["products\\\\September2020\\\\JEBFjumM0H1rpmrX2sZE.jpg"]',
                'created_at' => '2020-09-02 21:14:19',
                'updated_at' => '2020-09-02 21:14:19',
            ),
            64 => 
            array (
                'id' => 93,
                'name' => 'Peškiri mali',
                'slug' => 'peskiri-mali',
                'details' => NULL,
                'price' => 130,
                'description' => NULL,
                'quantity' => 10,
                'category_id' => 91,
                'manufacturer_id' => 18,
                'image' => 'products\\September2020\\h61UGAe8J57I7pSmMWba.jpg',
                'images' => '["products\\\\September2020\\\\KiPir7ZbOggnwO2TtVH9.jpg"]',
                'created_at' => '2020-09-02 21:17:46',
                'updated_at' => '2020-09-02 21:17:46',
            ),
            65 => 
            array (
                'id' => 94,
                'name' => 'Trenerka za devojčice Panter novo',
                'slug' => 'trenerka-za-devojcice-panter-novo',
                'details' => '62 %pamuk, 38 % poliester',
                'price' => 2990,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 50,
                'manufacturer_id' => 3,
                'image' => 'products\\September2020\\qc80eNJc1bCkFUdXFgun.jpg',
                'images' => NULL,
                'created_at' => '2020-09-02 21:19:58',
                'updated_at' => '2020-09-02 21:19:58',
            ),
            66 => 
            array (
                'id' => 95,
                'name' => 'Donji deo trenerke bebe',
                'slug' => 'donji-deo-trenerke-bebe',
                'details' => '100% pamuk',
                'price' => 650,
                'description' => NULL,
                'quantity' => 6,
                'category_id' => 32,
                'manufacturer_id' => 3,
                'image' => 'products\\September2020\\sa75XG88NFjtt7WUe3iF.jpg',
                'images' => NULL,
                'created_at' => '2020-09-02 21:22:39',
                'updated_at' => '2020-09-02 21:22:39',
            ),
            67 => 
            array (
                'id' => 96,
                'name' => 'Pantalone devojčice sa ranflom',
                'slug' => 'pantalone-devojcice-sa-ranflom',
                'details' => '100% pamuk',
                'price' => 1080,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 49,
                'manufacturer_id' => 2,
                'image' => 'products\\September2020\\ImXgXWL5L40RP13lbpk7.jpg',
                'images' => NULL,
                'created_at' => '2020-09-02 21:26:52',
                'updated_at' => '2020-09-02 21:39:06',
            ),
            68 => 
            array (
                'id' => 97,
                'name' => 'Donji deo trenerke crni Kid Star',
                'slug' => 'donji-deo-trenerke-crni-kid-star',
                'details' => '100% pamuk',
                'price' => 1120,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 50,
                'manufacturer_id' => 5,
                'image' => 'products\\September2020\\8Zgcv2fjTt2Me3Cek6b0.jpg',
                'images' => NULL,
                'created_at' => '2020-09-02 21:37:12',
                'updated_at' => '2020-09-02 21:40:46',
            ),
            69 => 
            array (
                'id' => 98,
                'name' => 'Donji deo trenerke Model sivi',
                'slug' => 'donji-deo-trenerke-model-sivi',
                'details' => '94.5% pamuk 5,5%elastan',
                'price' => 990,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 50,
                'manufacturer_id' => 19,
                'image' => 'products\\September2020\\ueM9t6zwQEuiQNW2XLLL.jpg',
                'images' => NULL,
                'created_at' => '2020-09-02 21:43:07',
                'updated_at' => '2020-09-02 21:45:34',
            ),
            70 => 
            array (
                'id' => 99,
                'name' => 'Helanke Star',
                'slug' => 'helanke-star',
                'details' => '95% pamuk, 5% elastan',
                'price' => 690,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 48,
                'manufacturer_id' => 5,
                'image' => 'products\\September2020\\0Nw0QKyODn5Zh2H6REEs.jpg',
                'images' => '["products\\\\September2020\\\\uIOULWIHn9WskPqV9ice.jpg","products\\\\September2020\\\\69Es6Y36DFX0L56IF6zi.jpg"]',
                'created_at' => '2020-09-02 21:49:54',
                'updated_at' => '2020-09-02 21:49:54',
            ),
            71 => 
            array (
                'id' => 100,
                'name' => 'Helanke Model Kids raznobojne',
                'slug' => 'helanke-model-kids-raznobojne',
                'details' => '95% pamuk, 5% elastan',
                'price' => 550,
                'description' => NULL,
                'quantity' => 10,
                'category_id' => 48,
                'manufacturer_id' => 2,
                'image' => 'products\\September2020\\y7088W251fdpIK6JXkoo.jpg',
                'images' => '["products\\\\September2020\\\\xZKMweRKQ783hOITnDbZ.jpg"]',
                'created_at' => '2020-09-02 21:53:07',
                'updated_at' => '2020-09-02 21:53:07',
            ),
            72 => 
            array (
                'id' => 101,
                'name' => 'Helanke za devojčice Wolf tufnice',
                'slug' => 'helanke-za-devojcice-wolf-tufnice',
                'details' => '95% pamuk, 5% elastan',
                'price' => 760,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 48,
                'manufacturer_id' => 20,
                'image' => 'products\\September2020\\8M7G5OOn0GWQkKP0MqSx.jpg',
                'images' => '["products\\\\September2020\\\\6480Qnsrhb5oAXbLNtYe.jpg"]',
                'created_at' => '2020-09-03 08:02:26',
                'updated_at' => '2020-09-03 08:20:53',
            ),
            73 => 
            array (
                'id' => 102,
                'name' => 'Duks yza devojčice Love',
                'slug' => 'duks-yza-devojcice-love',
                'details' => '95% pamuk, 5% elastan',
                'price' => 750,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 53,
                'manufacturer_id' => 2,
                'image' => 'products\\September2020\\ZzcVUrirzFPMRKUPT2te.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 08:10:03',
                'updated_at' => '2020-09-03 08:10:03',
            ),
            74 => 
            array (
                'id' => 103,
                'name' => 'Duks Model Girl',
                'slug' => 'duks-model-girl',
                'details' => '94.5% pamuk 5,5%elastan',
                'price' => 1080,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 53,
                'manufacturer_id' => 19,
                'image' => 'products\\September2020\\B63zQwus5tVSMELYkQCm.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 08:13:19',
                'updated_at' => '2020-09-03 08:13:19',
            ),
            75 => 
            array (
                'id' => 104,
                'name' => 'Duks za devojčice Model Kids',
                'slug' => 'duks-za-devojcice-model-kids',
                'details' => '93,3% pamuk , 6,7%elastab',
                'price' => 1450,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 53,
                'manufacturer_id' => 2,
                'image' => 'products\\September2020\\hWa32V5NS8EiP1JIdBnP.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 08:18:57',
                'updated_at' => '2020-09-03 08:18:57',
            ),
            76 => 
            array (
                'id' => 105,
                'name' => 'Helanke za devojčice Wolf zvezdice',
                'slug' => 'helanke-za-devojcice-wolf-zvezdice',
                'details' => '95% pamuk, 5% elastan',
                'price' => 760,
                'description' => NULL,
                'quantity' => 1,
                'category_id' => 48,
                'manufacturer_id' => 20,
                'image' => 'products\\September2020\\MrUOmdKL4wTQGMgrYoPw.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 08:23:06',
                'updated_at' => '2020-09-03 08:23:06',
            ),
            77 => 
            array (
                'id' => 106,
                'name' => 'Duks za devojčice sivi zvezdice Model',
                'slug' => 'duks-za-devojcice-sivi-zvezdice-model',
                'details' => '95% pamuk, 5% elastan',
                'price' => 970,
                'description' => NULL,
                'quantity' => 4,
                'category_id' => 29,
                'manufacturer_id' => 19,
                'image' => 'products\\September2020\\gg4tRb8nrfBCofl21mPW.jpg',
                'images' => '["products\\\\September2020\\\\HIxZ5IReqKfEWmwYTiWb.jpg","products\\\\September2020\\\\FvvT9Was4WS6Qo7Juq5j.jpg"]',
                'created_at' => '2020-09-03 08:24:57',
                'updated_at' => '2020-09-03 08:30:42',
            ),
            78 => 
            array (
                'id' => 107,
                'name' => 'Duks za devojčice Model Šljokice',
                'slug' => 'duks-za-devojcice-model-sljokice',
                'details' => '94.5% pamuk 5,5%elastan',
                'price' => 970,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 53,
                'manufacturer_id' => 19,
                'image' => 'products\\September2020\\R9DtBpLXyiZbuakS4asx.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 08:34:34',
                'updated_at' => '2020-09-03 08:34:34',
            ),
            79 => 
            array (
                'id' => 108,
                'name' => 'Majica za devojčice BY MG',
                'slug' => 'majica-za-devojcice-by-mg',
                'details' => '95% pamuk, 5% elastan',
                'price' => 930,
                'description' => NULL,
                'quantity' => 2,
                'category_id' => 45,
                'manufacturer_id' => 19,
                'image' => 'products\\September2020\\5aV0lTvkLynobyQt77Z1.jpg',
                'images' => '["products\\\\September2020\\\\1MIi1PpVqnKAZYgbLeYK.jpg"]',
                'created_at' => '2020-09-03 08:37:17',
                'updated_at' => '2020-09-03 08:37:17',
            ),
            80 => 
            array (
                'id' => 109,
                'name' => 'Majica srca Bambino',
                'slug' => 'majica-srca-bambino',
                'details' => '95% pamuk, 5% elastan',
                'price' => 750,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 45,
                'manufacturer_id' => 1,
                'image' => 'products\\September2020\\URhxUV4Lg7UlkyWPGSSH.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 08:39:09',
                'updated_at' => '2020-09-03 08:39:09',
            ),
            81 => 
            array (
                'id' => 110,
                'name' => 'Devojčice duks Bambino teget',
                'slug' => 'devojcice-duks-bambino-teget',
                'details' => '92% pamuk , 8%elastann',
                'price' => 1900,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 53,
                'manufacturer_id' => 1,
                'image' => 'products\\September2020\\YBTVLuPGQQyMy69mhyrm.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 08:41:15',
                'updated_at' => '2020-09-03 08:41:15',
            ),
            82 => 
            array (
                'id' => 111,
                'name' => 'Devojčice duks Bambino teget veći',
                'slug' => 'devojcice-duks-bambino-teget-veci',
                'details' => '92% pamuk , 8%elastann',
                'price' => 2300,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 53,
                'manufacturer_id' => 1,
                'image' => 'products\\September2020\\fD4vrkc4iC5RR71AFfwn.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 08:42:22',
                'updated_at' => '2020-09-03 08:42:22',
            ),
            83 => 
            array (
                'id' => 112,
                'name' => 'Donji deo trenerke',
                'slug' => 'donji-deo-trenerke',
                'details' => '95% pamuk, 5% likra',
                'price' => 560,
                'description' => NULL,
                'quantity' => 3,
                'category_id' => 32,
                'manufacturer_id' => 5,
                'image' => 'products\\September2020\\t4MiS1ZSWMrt9TFRx83w.jpg',
                'images' => '["products\\\\September2020\\\\hXPYUfIVrd9UuG4NlVqh.jpg"]',
                'created_at' => '2020-09-03 08:46:04',
                'updated_at' => '2020-09-03 08:46:04',
            ),
            84 => 
            array (
                'id' => 113,
                'name' => 'Donji deo Kid star Print',
                'slug' => 'donji-deo-kid-star-print',
                'details' => '94.5% pamuk 5,5%elastan',
                'price' => 1080,
                'description' => NULL,
                'quantity' => 4,
                'category_id' => 32,
                'manufacturer_id' => 5,
                'image' => 'products\\September2020\\UmqWaSvZrG6kMTGB9phI.jpg',
                'images' => '["products\\\\September2020\\\\FN8Nmh2uNXBFySkv4pue.jpg","products\\\\September2020\\\\QEB5iIvyFLZOGEpM87oZ.jpg"]',
                'created_at' => '2020-09-03 08:48:19',
                'updated_at' => '2020-09-03 08:50:30',
            ),
            85 => 
            array (
                'id' => 114,
                'name' => 'Trenerke uže Kid star',
                'slug' => 'trenerke-uze-kid-star',
                'details' => '95% pamuk, 5% elastan',
                'price' => 790,
                'description' => NULL,
                'quantity' => 4,
                'category_id' => 32,
                'manufacturer_id' => 5,
                'image' => 'products\\September2020\\piqd5s4gDIBaOhpkc0cx.jpg',
                'images' => '["products\\\\September2020\\\\ASHupuvkgRdtZ3dr9Mjj.jpg"]',
                'created_at' => '2020-09-03 08:53:21',
                'updated_at' => '2020-09-03 08:53:21',
            ),
            86 => 
            array (
                'id' => 115,
                'name' => 'Trenerka donji deo Bambino za dečake',
                'slug' => 'trenerka-donji-deo-bambino-za-decake',
                'details' => '95% pamuk, 5% elastan',
                'price' => 988,
                'description' => NULL,
                'quantity' => 6,
                'category_id' => 32,
                'manufacturer_id' => 1,
                'image' => 'products\\September2020\\Qi7ocYEXcr6lcbhRBzBM.jpg',
                'images' => '["products\\\\September2020\\\\ak2GQJPWQiLMD2QgBhX9.jpg","products\\\\September2020\\\\IK2P51a6PBn0M45gzU6n.jpg"]',
                'created_at' => '2020-09-03 08:55:44',
                'updated_at' => '2020-09-03 08:55:44',
            ),
            87 => 
            array (
                'id' => 116,
                'name' => 'Jakna za jesen dečaci Bambino',
                'slug' => 'jakna-za-jesen-decaci-bambino',
                'details' => NULL,
                'price' => 2600,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 35,
                'manufacturer_id' => 1,
                'image' => 'products\\September2020\\euzmy50vlaiT2L2eAVdz.jpg',
                'images' => '["products\\\\September2020\\\\tza2LCCXHETO0WzkyjOp.jpg"]',
                'created_at' => '2020-09-03 09:06:17',
                'updated_at' => '2020-09-03 09:06:17',
            ),
            88 => 
            array (
                'id' => 117,
                'name' => 'Prsluk za dečake Bambino',
                'slug' => 'prsluk-za-decake-bambino',
                'details' => NULL,
                'price' => 2100,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 97,
                'manufacturer_id' => 1,
                'image' => 'products\\September2020\\mQz9sbCR9I5iqQAQRaq5.jpg',
                'images' => '["products\\\\September2020\\\\RCn7W8Ss2JSB6Q3xHrwg.jpg"]',
                'created_at' => '2020-09-03 09:08:44',
                'updated_at' => '2020-09-03 09:08:44',
            ),
            89 => 
            array (
                'id' => 118,
                'name' => 'Dečaci duks Bambino print',
                'slug' => 'decaci-duks-bambino-print',
                'details' => '94.5% pamuk 5,5%elastan',
                'price' => 1400,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 29,
                'manufacturer_id' => 1,
                'image' => 'products\\September2020\\frQXxOJjXjISMZPcvoUm.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 09:10:41',
                'updated_at' => '2020-09-03 09:10:41',
            ),
            90 => 
            array (
                'id' => 119,
                'name' => 'Jaknica šarena Bambino za devojčice',
                'slug' => 'jaknica-sarena-bambino-za-devojcice',
                'details' => '92% pamuk , 8%elastann',
                'price' => 2600,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 51,
                'manufacturer_id' => 1,
                'image' => 'products\\September2020\\e0gzvgpAkTxsf805ahjK.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 09:13:13',
                'updated_at' => '2020-09-03 09:13:13',
            ),
            91 => 
            array (
                'id' => 120,
                'name' => 'Prsluk Bambino za devojčice',
                'slug' => 'prsluk-bambino-za-devojcice',
                'details' => '94.5% pamuk 5,5%elastan',
                'price' => 1750,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 98,
                'manufacturer_id' => 1,
                'image' => 'products\\September2020\\ofHjsC1SOo1D0AKZOxs6.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 09:15:48',
                'updated_at' => '2020-09-03 09:15:48',
            ),
            92 => 
            array (
                'id' => 121,
                'name' => 'Donji deo trenerke Kid star Pow',
                'slug' => 'donji-deo-trenerke-kid-star-pow',
                'details' => '95% pamuk, 5% elastan',
                'price' => 690,
                'description' => NULL,
                'quantity' => 4,
                'category_id' => 32,
                'manufacturer_id' => 5,
                'image' => 'products\\September2020\\DoDoIlv6DTGI0CccevSY.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 09:19:28',
                'updated_at' => '2020-09-03 09:19:28',
            ),
            93 => 
            array (
                'id' => 122,
                'name' => 'Majica za dečake Robot Bambino',
                'slug' => 'majica-za-decake-robot-bambino',
                'details' => '95% pamuk, 5% elastan',
                'price' => 730,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 28,
                'manufacturer_id' => 1,
                'image' => 'products\\September2020\\RbahhuU9bnJ5kGRVBZd0.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 09:34:12',
                'updated_at' => '2020-09-03 09:34:12',
            ),
            94 => 
            array (
                'id' => 123,
                'name' => 'Majica za dečake Žabac Bambino',
                'slug' => 'majica-za-decake-zabac-bambino',
                'details' => '95% pamuk, 5% elastan',
                'price' => 730,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 45,
                'manufacturer_id' => 1,
                'image' => 'products\\September2020\\k8ccZHElbhp9KfIszLOJ.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 09:35:34',
                'updated_at' => '2020-09-03 09:35:34',
            ),
            95 => 
            array (
                'id' => 124,
                'name' => 'Majica za devojčice crvena Bambino',
                'slug' => 'majica-za-devojcice-crvena-bambino',
                'details' => '95% pamuk, 5% elastan',
                'price' => 730,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 28,
                'manufacturer_id' => 1,
                'image' => 'products\\September2020\\wFkg0Q5JC2HiSFzZevrX.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 09:36:40',
                'updated_at' => '2020-09-03 09:36:40',
            ),
            96 => 
            array (
                'id' => 125,
                'name' => 'Majica za dečake na dugmiće Bambino',
                'slug' => 'majica-za-decake-na-dugmice-bambino',
                'details' => '95% pamuk, 5% elastan',
                'price' => 950,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 28,
                'manufacturer_id' => 1,
                'image' => 'products\\September2020\\6y4Sd8omWM20wKEE7wn8.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 09:38:03',
                'updated_at' => '2020-09-03 09:38:03',
            ),
            97 => 
            array (
                'id' => 126,
                'name' => 'Majica za devojčice Bambino mede',
                'slug' => 'majica-za-devojcice-bambino-mede',
                'details' => '100% pamuk',
                'price' => 730,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 45,
                'manufacturer_id' => 1,
                'image' => 'products\\September2020\\5wVV7fh9XHnAZ7yAdfRl.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 09:42:03',
                'updated_at' => '2020-09-03 09:42:03',
            ),
            98 => 
            array (
                'id' => 127,
                'name' => 'Majica za devojčice Bambino Cats',
                'slug' => 'majica-za-devojcice-bambino-cats',
                'details' => '100% pamuk',
                'price' => 730,
                'description' => NULL,
                'quantity' => 5,
                'category_id' => 45,
                'manufacturer_id' => 1,
                'image' => 'products\\September2020\\QhaFA4iYkASibIXXCXAf.jpg',
                'images' => NULL,
                'created_at' => '2020-09-03 09:43:21',
                'updated_at' => '2020-09-03 09:43:21',
            ),
        ));
        
        
    }
}